import { useEffect, useMemo, useState } from "react";
import DashboardShell from "@/components/DashboardShell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";

type Contact = { id: string; name: string | null; phone_number: string; last_message_at: string | null; created_at: string; metadata?: { stage_id: string | null; owner_id: string | null; notes: string | null }; stage?: { name: string } };
const db = supabase as any;
export default function CRM() {
  const { user } = useAuth(); const [contacts, setContacts] = useState<Contact[]>([]); const [stages, setStages] = useState<{ id: string; name: string }[]>([]); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<Contact | null>(null); const [kanban, setKanban] = useState(false);
  const load = async () => { if (!user) return; const [{ data: contacts }, { data: stages }] = await Promise.all([db.from("whatsapp_contacts").select("id,name,phone_number,last_message_at,created_at").eq("user_id", user.id).order("last_message_at", { ascending: false, nullsFirst: false }), db.from("crm_stages").select("id,name").eq("user_id", user.id).order("position")]); const { data: meta } = await db.from("crm_contact_metadata").select("contact_id,stage_id,owner_id,notes").eq("user_id", user.id); const stageMap = new Map((stages || []).map((stage: { id: string; name: string }) => [stage.id, stage])); const metaMap = new Map((meta || []).map((item: { contact_id: string; stage_id: string | null; owner_id: string | null; notes: string | null }) => [item.contact_id, item])); setStages(stages || []); setContacts((contacts || []).map((contact: Contact) => ({ ...contact, metadata: metaMap.get(contact.id), stage: stageMap.get(metaMap.get(contact.id)?.stage_id || "") }))); };
  useEffect(() => { void load(); }, [user]);
  const filtered = useMemo(() => contacts.filter((contact) => `${contact.name || ""} ${contact.phone_number}`.toLowerCase().includes(search.toLowerCase())), [contacts, search]);
  const setStage = async (contact: Contact, stageId: string) => { if (!user) return; await db.from("crm_contact_metadata").upsert({ contact_id: contact.id, user_id: user.id, stage_id: stageId }, { onConflict: "contact_id" }); await db.from("crm_activities").insert({ user_id: user.id, contact_id: contact.id, activity_type: "stage_changed", description: "Etapa alterada" }); load(); };
  return <DashboardShell title="CRM" description="Organize contactos, oportunidades e histórico do negócio."><div className="flex flex-wrap items-center justify-between gap-3"><Input className="max-w-md" placeholder="Pesquisar contactos" value={search} onChange={(e) => setSearch(e.target.value)} /><Button variant="outline" onClick={() => setKanban(!kanban)}>{kanban ? "Ver lista" : "Ver Kanban"}</Button></div>{kanban ? <div className="grid gap-3 overflow-x-auto md:grid-cols-4 xl:grid-cols-7">{stages.map((stage) => <Card key={stage.id} className="min-w-[190px]"><CardHeader><CardTitle className="text-sm">{stage.name}</CardTitle></CardHeader><CardContent className="space-y-2">{filtered.filter((contact) => contact.metadata?.stage_id === stage.id).map((contact) => <button type="button" key={contact.id} onClick={() => setSelected(contact)} className="w-full rounded border p-2 text-left text-sm hover:border-primary">{contact.name || contact.phone_number}</button>)}</CardContent></Card>)}</div> : <Card><CardHeader><CardTitle>Contactos ({filtered.length})</CardTitle></CardHeader><CardContent className="overflow-auto"><table className="w-full min-w-[650px] text-sm"><thead><tr className="border-b text-left"><th className="py-3">Nome</th><th>Telefone</th><th>Etapa</th><th>Última interação</th><th>Criado em</th></tr></thead><tbody>{filtered.map((contact) => <tr key={contact.id} className="cursor-pointer border-b hover:bg-muted/40" onClick={() => setSelected(contact)}><td className="py-3 font-medium">{contact.name || "Sem nome"}</td><td>{contact.phone_number}</td><td>{contact.stage?.name || "Novo"}</td><td>{contact.last_message_at ? new Date(contact.last_message_at).toLocaleString("pt-AO") : "-"}</td><td>{new Date(contact.created_at).toLocaleDateString("pt-AO")}</td></tr>)}</tbody></table></CardContent></Card>}<Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent><DialogHeader><DialogTitle>{selected?.name || selected?.phone_number}</DialogTitle></DialogHeader>{selected && <div className="space-y-4 text-sm"><div>Telefone: {selected.phone_number}</div><div>Etapa: <select className="rounded border p-2" value={selected.metadata?.stage_id || stages[0]?.id || ""} onChange={(e) => setStage(selected, e.target.value)}>{stages.map((stage) => <option key={stage.id} value={stage.id}>{stage.name}</option>)}</select></div><div>Última interação: {selected.last_message_at ? new Date(selected.last_message_at).toLocaleString("pt-AO") : "-"}</div><div>Notas: {selected.metadata?.notes || "Sem notas"}</div><Button variant="outline" onClick={() => setSelected(null)}>Fechar</Button></div>}</DialogContent></Dialog></DashboardShell>;
}
