import { FormEvent, useEffect, useState } from "react";
import DashboardShell from "@/components/DashboardShell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/hooks/useAuth";
import { usePlanEntitlements } from "@/hooks/usePlanEntitlements";
import { supabase } from "@/integrations/supabase/client";
const db = supabase as any;
export default function FollowUp() { const { user } = useAuth(); const { entitlements, planName, loading } = usePlanEntitlements(); const [rules, setRules] = useState<any[]>([]); const [form, setForm] = useState({ name: "", delay_minutes: "120", max_attempts: "3", ai_instruction: "" }); const load = async () => { if (!user) return; const { data } = await db.from("follow_up_rules").select("*").eq("user_id", user.id).order("created_at", { ascending: false }); setRules(data || []); }; useEffect(() => { void load(); }, [user]); const create = async (event: FormEvent) => { event.preventDefault(); if (!user) return; const { error } = await db.from("follow_up_rules").insert({ user_id: user.id, name: form.name, delay_minutes: Number(form.delay_minutes), max_attempts: Number(form.max_attempts), ai_instruction: form.ai_instruction, is_active: false }); if (!error) { setForm({ name: "", delay_minutes: "120", max_attempts: "3", ai_instruction: "" }); load(); } }; if (loading) return <DashboardShell title="Follow Up IA" description="A carregar acesso...">A carregar...</DashboardShell>; if (!entitlements.followUp) return <DashboardShell title="Follow Up IA" description="Recupere oportunidades de conversas existentes."><Card><CardContent className="space-y-3 p-6"><CardTitle>Follow Up IA</CardTitle><p className="text-sm text-muted-foreground">Disponível a partir do plano Growth. Plano atual: {planName}.</p><Button onClick={() => window.location.assign("/recargas")}>Fazer upgrade</Button></CardContent></Card></DashboardShell>; return <DashboardShell title="Follow Up IA" description="Configure regras para conversas que ficaram sem conclusão."><Card><CardHeader><CardTitle>Nova regra</CardTitle></CardHeader><CardContent><form onSubmit={create} className="grid gap-3 md:grid-cols-2"><Input required placeholder="Nome da regra" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><Input required type="number" min="1" placeholder="Esperar minutos" value={form.delay_minutes} onChange={(e) => setForm({ ...form, delay_minutes: e.target.value })} /><Input required type="number" min="1" placeholder="Máximo de tentativas" value={form.max_attempts} onChange={(e) => setForm({ ...form, max_attempts: e.target.value })} /><Textarea className="md:col-span-2" placeholder="Instrução para a IA" value={form.ai_instruction} onChange={(e) => setForm({ ...form, ai_instruction: e.target.value })} /><Button className="w-fit">Guardar regra</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Regras configuradas</CardTitle></CardHeader><CardContent className="space-y-2">{rules.map((rule) => <div key={rule.id} className="rounded border p-3"><div className="font-medium">{rule.name}</div><div className="text-sm text-muted-foreground">{rule.delay_minutes} minutos · {rule.max_attempts} tentativas · {rule.is_active ? "Ativa" : "Inativa"}</div></div>)}</CardContent></Card></DashboardShell>; }
